app:
  web:
    path: ${WEB_ROOT:classpath:public}
server:
  port: ${SERVER_PORT:8989}

spring:
  freemarker:
    check-template-location: false
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false
#  pid:
#    file: /xx/xadmin.pid

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


  application:
    name: xadmin
    #cache:
    #  type: jcache
    #  jcache:
    #    config: classpath:ehcache.xml
task:
  pool:
    core-pool-size: 10
    max-pool-size: 30
    keep-alive-seconds: 60
    queue-capacity: 50

code:
  expiration: 300

rsa:
  private_key: MIIBUwIBADANBgkqhkiG9w0BAQEFAASCAT0wggE5AgEAAkEAl1HXyvWmct4bTzDQdyLMemvzcMt+qKK9WZOhoAI/yEJ8N6MsGztd0nwxbyOfy0eDZ9WQ9PXr0dAM73vNBe19wQIDAQABAkBvzXKpbNLssBpxalm8jKOUGEqoHlKY+pT4qFGUzdSeew4ptYO6Kv67/BSq/uWRR26jPALN4n35u9IAG78pEu6BAiEAybsWfVg7DGJQLj/1M/wXiP8Yt+Bl8pme8/PvDqGyjTkCIQDABwOQ2bL84rkgK/VqUUfwSVyww2m1QCI7fCi7G/18yQIgfLKgOUUT4xjWlXBFoye+aJm/btJQUoExZ30vFa1QUMkCIHlJdNUey9Cym19YpI/ceuWoUKVNKA1VTsnnqApWqYsRAiAR6O6Tf+IFeCXIfxea4VsLz4zvaXS5QKvlISyrr9MhOg==
