app:
  web:
    path: ${WEB_ROOT:classpath:public}
server:
  port: ${SERVER_PORT:8989}

spring:
  freemarker:
    check-template-location: false
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false
#  pid:
#    file: /xx/xadmin.pid

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


  application:
    name: xadmin
    #cache:
    #  type: jcache
    #  jcache:
    #    config: classpath:ehcache.xml


task:
  pool:
    core-pool-size: 10
    max-pool-size: 30
    keep-alive-seconds: 60
    queue-capacity: 50

code:
  expiration: 300

rsa:
  private_key: MIIBUwIBADANBgkqhkiG9w0BAQEFAASCAT0wggE5AgEAAkEAl1HXyvWmct4bTzDQdyLMemvzcMt+qKK9WZOhoAI/yEJ8N6MsGztd0nwxbyOfy0eDZ9WQ9PXr0dAM73vNBe19wQIDAQABAkBvzXKpbNLssBpxalm8jKOUGEqoHlKY+pT4qFGUzdSeew4ptYO6Kv67/BSq/uWRR26jPALN4n35u9IAG78pEu6BAiEAybsWfVg7DGJQLj/1M/wXiP8Yt+Bl8pme8/PvDqGyjTkCIQDABwOQ2bL84rkgK/VqUUfwSVyww2m1QCI7fCi7G/18yQIgfLKgOUUT4xjWlXBFoye+aJm/btJQUoExZ30vFa1QUMkCIHlJdNUey9Cym19YpI/ceuWoUKVNKA1VTsnnqApWqYsRAiAR6O6Tf+IFeCXIfxea4VsLz4zvaXS5QKvlISyrr9MhOg==


# 登录相关配置
login:
  #  是否限制单用户登录
  single-login: false
  # Redis用户登录缓存配置
  user-cache:
    # 存活时间/秒
    idle-time: 7200
  #  验证码
  login-code:
    #  验证码类型配置 查看 LoginProperties 类
    code-type: arithmetic
    #  登录图形验证码有效时间/分钟
    expiration: 2
    #  验证码高度
    width: 111
    #  验证码宽度
    height: 36
    # 内容长度
    length: 2
    # 字体名称，为空则使用默认字体，如遇到线上乱码，设置其他字体即可
    font-name:
    # 字体大小
    font-size: 25

#jwt
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 令牌过期时间 此处单位/毫秒 ，默认2小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
  token-validity-in-seconds: 7200000
  # 在线用户key
  online-key: online-token-
  # 验证码
  code-key: code-key-
  # token 续期检查时间范围（默认30分钟，单位默认毫秒），在token即将过期的一段时间内用户操作了，则给用户的token续期
  detect: 1800000
  # 续期时间范围，默认 1小时，这里单位毫秒
  renew: 3600000

# 文件存储路径
file:
  mac:
    path: ${UPLOAD_PATH:/data/xadmin}/file/
    avatar: ${UPLOAD_PATH:/data/xadmin}/avatar/
  linux:
    path: ${UPLOAD_PATH:/data/xadmin}/file/
    avatar: ${UPLOAD_PATH:/data/xadmin}/avatar/
  windows:
    path: ${UPLOAD_PATH:C:\xadmin}\file\
    avatar: ${UPLOAD_PATH:C:\xadmin}\avatar\
  # 文件大小 /M
  maxSize: 100
  avatarMaxSize: 5


ip:
  local-parsing: true
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  metrics:
#    tags:
#      application: ${spring.application.name}
#    export:
#      prometheus:
#        enabled: true
#        step: 1m
#        descriptions: true
#